<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Controllers\NewsController.cs" />
    <Compile Remove="Controllers\PasswordController.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="Views\CheckPassword\CheckPassword.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Controllers\.txt" />
    <None Remove="Controllers\NewFile.txt" />
    <None Remove="Services\NewFile.txt" />
    <None Remove="Views\CheckPassword\NewFile.txt" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.10">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="NewsAPI" Version="0.7.0" />
  </ItemGroup>

</Project>
